PasswordAuthentication no
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin prohibit-password
PubkeyAuthentication yes
X11Forwarding no
MaxAuthTries 3
AllowTcpForwarding yes
ClientAliveInterval 30
ClientAliveCountMax 3
